services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tada-backend-prod-hetzner
    ports:
      - "3002:3002"
    env_file:
      - ./backend/.env.production
    command: sh -c "npm run start"
    networks:
      - rental_network_stage
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  rental_network_stage:
